name: Update Literature Page

on:
  schedule:
    - cron: '0 0 * * 0' # Schedule to run daily
  workflow_dispatch: # Allow manual triggering

jobs:
  update-literature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Transcribe videos
        run: node scripts/transcribe_videos.mjs

      - name: Extract information
        run: node scripts/extract_information.mjs

      - name: Update HTML
        run: node scripts/update_html.mjs

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update literature page with new video information'
          git push
