name: Update Locations

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  push:
    branches:
      - main

jobs:
  update-locations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r ./requirements.txt

    - name: Run update_locations.py
      run: python scripts/update_locations.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add locations.html
        git commit -m 'Update locations page'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
